version: '3.7'

services:
  mysql:
    container_name: fs_app_mysql
    image: mysql:latest
    volumes:
      - ./www:/var/www
      - ./mysql-data:/var/lib/mysql
    restart: always
    networks:
      - fs_app
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: fs_app_db
      MYSQL_USER: fs_app
      MYSQL_PASSWORD: fs_app
    command: [ "--default-authentication-plugin=mysql_native_password" ]

  php:
    container_name: fs_app_php
    build: ./images/php82fpm
    volumes:
      - ./www:/var/www
      - ./images/php82fpm/php.ini:/usr/local/etc/php/conf.d/php.ini
    restart: always
    networks:
      - fs_app
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - mysql

networks:
  fs_app:
    name: fs_app